export const routes = {
  signIn: '/sign-in',
  signUp: 'sign-up',
  joinProject: '/join-to-project',
  startProject: '/start-new-project',
  projects: '/projects',
  team: '/project/:id/team',
  memberDetails: '/project/:id/team/:id',
  announcements: '/project/:id/announcements',
  announcementsDetails: '/project/:id/announcements/:id',
  statistics: '/project/:id/statistics',
  backlog: '/project/:id/backlog',
  backlogDetails: '/project/:id/backlog/:id',
  sprints: '/project/:id/sprints',
  sprintDetails: '/project/:id/sprints/:id',
  selectRole: '/project/:id/select-role',
  account: '/project/:id/account',
};
